# Generated by Django 6.0.1 on 2026-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_otp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(blank=True, choices=[('signup', 'Signup'), ('reset_password', 'Reset_Password')], max_length=25, null=True),
        ),
    ]
