# Generated by Django 6.0.1 on 2026-02-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_otp_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='purpose',
        ),
    ]
